CREATE TABLE usuarios (
    /*id INT AUTO_INCREMENT PRIMARY KEY,*/
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(15) NOT NULL
);
